developer_token: "lcZ3RRE00HWy2i4quLMNuQ"

client_id: "678557618747-g5s51o62h57ksc9kle428goahpql4l5p.apps.googleusercontent.com"

client_secret: "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"

refresh_token: "1//0g_3ZFtz0qY-yCgYIARAAGBASNwF-L9IrJo03zoUazUJ7xzpveUPPAuc60M6vvFQeuKpBDjEP8QEJOcJuDC7NEMj5p2J-Sn8ge0k"

login_customer_id: "5558904658"

use_proto_plus: True